window.BENCHMARK_DATA = {
  "lastUpdate": 1746024320776,
  "repoUrl": "https://github.com/cryspen/rosenpass",
  "entries": {
    "rosenpass protocol benchmarks": [
      {
        "commit": {
          "author": {
            "email": "jan@cryspen.com",
            "name": "Jan Winkelmann (keks)",
            "username": "keks"
          },
          "committer": {
            "email": "jan@cryspen.com",
            "name": "Jan Winkelmann (keks)",
            "username": "keks"
          },
          "distinct": true,
          "id": "58a58300a4424980411920ab38ea8aaa4835ef05",
          "message": "fix binning in protocol benchmark",
          "timestamp": "2025-04-30T16:42:55+02:00",
          "tree_id": "be22e7023ea3abb29a861bbe7da9d14df4664e8a",
          "url": "https://github.com/cryspen/rosenpass/commit/58a58300a4424980411920ab38ea8aaa4835ef05"
        },
        "date": 1746024320168,
        "bigger_is_better": false,
        "benches": [
          {
            "name": "ihi4",
            "unit": "ns/iter",
            "value": "16140",
            "range": "± 1",
            "category": "proto_run_V02",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86",
            "group": "below_ms"
          },
          {
            "name": "ihr5",
            "unit": "ns/iter",
            "value": "86856176",
            "range": "± 846141",
            "category": "proto_run_V02",
            "sampleSize": "2",
            "os": "linux",
            "arch": "x86",
            "group": "long"
          },
          {
            "name": "icr2",
            "unit": "ns/iter",
            "value": "65953",
            "range": "± 1",
            "category": "proto_run_V02",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86",
            "group": "below_ms"
          },
          {
            "name": "icr3",
            "unit": "ns/iter",
            "value": "14096",
            "range": "± 1",
            "category": "proto_run_V02",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86",
            "group": "below_ms"
          },
          {
            "name": "ihi2",
            "unit": "ns/iter",
            "value": "331",
            "range": "± 1",
            "category": "proto_run_V02",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86",
            "group": "below_us"
          },
          {
            "name": "rhr4",
            "unit": "ns/iter",
            "value": "122067",
            "range": "± 1",
            "category": "proto_run_V02",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86",
            "group": "below_ms"
          },
          {
            "name": "handle_init_hello",
            "unit": "ns/iter",
            "value": "91552705",
            "range": "± 1002312",
            "category": "proto_run_V02",
            "sampleSize": "2",
            "os": "linux",
            "arch": "x86",
            "group": "long"
          },
          {
            "name": "ihi5",
            "unit": "ns/iter",
            "value": "1851830",
            "range": "± 1",
            "category": "proto_run_V02",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86",
            "group": "medium"
          },
          {
            "name": "rhr3",
            "unit": "ns/iter",
            "value": "13916",
            "range": "± 1",
            "category": "proto_run_V02",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86",
            "group": "below_ms"
          },
          {
            "name": "rhr5",
            "unit": "ns/iter",
            "value": "1727218",
            "range": "± 1",
            "category": "proto_run_V02",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86",
            "group": "medium"
          },
          {
            "name": "ici3",
            "unit": "ns/iter",
            "value": "14006",
            "range": "± 1",
            "category": "proto_run_V02",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86",
            "group": "below_ms"
          },
          {
            "name": "icr6",
            "unit": "ns/iter",
            "value": "50",
            "range": "± 1",
            "category": "proto_run_V02",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86",
            "group": "below_us"
          },
          {
            "name": "handle_resp_hello",
            "unit": "ns/iter",
            "value": "86129858",
            "range": "± 1",
            "category": "proto_run_V02",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86",
            "group": "long"
          },
          {
            "name": "ici4",
            "unit": "ns/iter",
            "value": "13906",
            "range": "± 1",
            "category": "proto_run_V02",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86",
            "group": "below_ms"
          },
          {
            "name": "handle_resp_conf",
            "unit": "ns/iter",
            "value": "1127240",
            "range": "± 1",
            "category": "proto_run_V02",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86",
            "group": "medium"
          },
          {
            "name": "ihi3",
            "unit": "ns/iter",
            "value": "83014",
            "range": "± 1",
            "category": "proto_run_V02",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86",
            "group": "below_ms"
          },
          {
            "name": "icr4",
            "unit": "ns/iter",
            "value": "14197",
            "range": "± 1",
            "category": "proto_run_V02",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86",
            "group": "below_ms"
          },
          {
            "name": "ihr6",
            "unit": "ns/iter",
            "value": "15800",
            "range": "± 511",
            "category": "proto_run_V02",
            "sampleSize": "2",
            "os": "linux",
            "arch": "x86",
            "group": "below_ms"
          },
          {
            "name": "handle_init_conf",
            "unit": "ns/iter",
            "value": "2112210",
            "range": "± 701051",
            "category": "proto_run_V02",
            "sampleSize": "2",
            "os": "linux",
            "arch": "x86",
            "group": "medium"
          },
          {
            "name": "handle_initiation",
            "unit": "ns/iter",
            "value": "5694258",
            "range": "± 1",
            "category": "proto_run_V02",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86",
            "group": "medium"
          },
          {
            "name": "rhr1",
            "unit": "ns/iter",
            "value": "241",
            "range": "± 1",
            "category": "proto_run_V02",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86",
            "group": "below_us"
          },
          {
            "name": "rhi3",
            "unit": "ns/iter",
            "value": "13986",
            "range": "± 1",
            "category": "proto_run_V02",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86",
            "group": "below_ms"
          },
          {
            "name": "ihr8",
            "unit": "ns/iter",
            "value": "14136",
            "range": "± 1",
            "category": "proto_run_V02",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86",
            "group": "below_ms"
          },
          {
            "name": "ihr1",
            "unit": "ns/iter",
            "value": "1967265",
            "range": "± 843291",
            "category": "proto_run_V02",
            "sampleSize": "2",
            "os": "linux",
            "arch": "x86",
            "group": "medium"
          },
          {
            "name": "ihr4",
            "unit": "ns/iter",
            "value": "18209",
            "range": "± 2420",
            "category": "proto_run_V02",
            "sampleSize": "2",
            "os": "linux",
            "arch": "x86",
            "group": "below_ms"
          },
          {
            "name": "rhi6",
            "unit": "ns/iter",
            "value": "7163",
            "range": "± 1",
            "category": "proto_run_V02",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86",
            "group": "below_ms"
          },
          {
            "name": "ihr7",
            "unit": "ns/iter",
            "value": "1134544",
            "range": "± 1",
            "category": "proto_run_V02",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86",
            "group": "medium"
          },
          {
            "name": "ihi6",
            "unit": "ns/iter",
            "value": "1149702",
            "range": "± 1",
            "category": "proto_run_V02",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86",
            "group": "medium"
          },
          {
            "name": "rhi7",
            "unit": "ns/iter",
            "value": "14156",
            "range": "± 1",
            "category": "proto_run_V02",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86",
            "group": "below_ms"
          },
          {
            "name": "rhr6",
            "unit": "ns/iter",
            "value": "2362341",
            "range": "± 1",
            "category": "proto_run_V02",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86",
            "group": "medium"
          },
          {
            "name": "ihi8",
            "unit": "ns/iter",
            "value": "14137",
            "range": "± 1",
            "category": "proto_run_V02",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86",
            "group": "below_ms"
          },
          {
            "name": "rhi5",
            "unit": "ns/iter",
            "value": "85927741",
            "range": "± 1",
            "category": "proto_run_V02",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86",
            "group": "long"
          },
          {
            "name": "rhi4",
            "unit": "ns/iter",
            "value": "121917",
            "range": "± 1",
            "category": "proto_run_V02",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86",
            "group": "below_ms"
          },
          {
            "name": "icr1",
            "unit": "ns/iter",
            "value": "2057893",
            "range": "± 755266",
            "category": "proto_run_V02",
            "sampleSize": "2",
            "os": "linux",
            "arch": "x86",
            "group": "medium"
          },
          {
            "name": "ihi7",
            "unit": "ns/iter",
            "value": "1140044",
            "range": "± 1",
            "category": "proto_run_V02",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86",
            "group": "medium"
          },
          {
            "name": "icr7",
            "unit": "ns/iter",
            "value": "12223",
            "range": "± 1",
            "category": "proto_run_V02",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86",
            "group": "below_ms"
          },
          {
            "name": "rhr7",
            "unit": "ns/iter",
            "value": "14157",
            "range": "± 1",
            "category": "proto_run_V02",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86",
            "group": "below_ms"
          },
          {
            "name": "ihi1",
            "unit": "ns/iter",
            "value": "1263604",
            "range": "± 1",
            "category": "proto_run_V02",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86",
            "group": "medium"
          },
          {
            "name": "ici7",
            "unit": "ns/iter",
            "value": "12093",
            "range": "± 1",
            "category": "proto_run_V02",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86",
            "group": "below_ms"
          },
          {
            "name": "icr3",
            "unit": "ns/iter",
            "value": "16021",
            "range": "± 1",
            "category": "proto_run_V03",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86",
            "group": "below_ms"
          },
          {
            "name": "ihr1",
            "unit": "ns/iter",
            "value": "2817068",
            "range": "± 1",
            "category": "proto_run_V03",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86",
            "group": "medium"
          },
          {
            "name": "ihr5",
            "unit": "ns/iter",
            "value": "87670167",
            "range": "± 1",
            "category": "proto_run_V03",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86",
            "group": "long"
          },
          {
            "name": "rhi3",
            "unit": "ns/iter",
            "value": "15909",
            "range": "± 1",
            "category": "proto_run_V03",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86",
            "group": "below_ms"
          },
          {
            "name": "rhr4",
            "unit": "ns/iter",
            "value": "134531",
            "range": "± 1",
            "category": "proto_run_V03",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86",
            "group": "below_ms"
          },
          {
            "name": "ihi4",
            "unit": "ns/iter",
            "value": "21009",
            "range": "± 1",
            "category": "proto_run_V03",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86",
            "group": "below_ms"
          },
          {
            "name": "rhi6",
            "unit": "ns/iter",
            "value": "8726",
            "range": "± 1",
            "category": "proto_run_V03",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86",
            "group": "below_ms"
          },
          {
            "name": "ihi3",
            "unit": "ns/iter",
            "value": "79639",
            "range": "± 1",
            "category": "proto_run_V03",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86",
            "group": "below_ms"
          },
          {
            "name": "icr6",
            "unit": "ns/iter",
            "value": "131",
            "range": "± 1",
            "category": "proto_run_V03",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86",
            "group": "below_us"
          },
          {
            "name": "ihr7",
            "unit": "ns/iter",
            "value": "2828219",
            "range": "± 1",
            "category": "proto_run_V03",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86",
            "group": "medium"
          },
          {
            "name": "ihi5",
            "unit": "ns/iter",
            "value": "3504579",
            "range": "± 1",
            "category": "proto_run_V03",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86",
            "group": "medium"
          },
          {
            "name": "handle_init_hello",
            "unit": "ns/iter",
            "value": "102609909",
            "range": "± 1",
            "category": "proto_run_V03",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86",
            "group": "long"
          },
          {
            "name": "ihi8",
            "unit": "ns/iter",
            "value": "15859",
            "range": "± 1",
            "category": "proto_run_V03",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86",
            "group": "below_ms"
          },
          {
            "name": "ihr6",
            "unit": "ns/iter",
            "value": "17453",
            "range": "± 1",
            "category": "proto_run_V03",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86",
            "group": "below_ms"
          },
          {
            "name": "ihi6",
            "unit": "ns/iter",
            "value": "2844149",
            "range": "± 1",
            "category": "proto_run_V03",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86",
            "group": "medium"
          },
          {
            "name": "rhi4",
            "unit": "ns/iter",
            "value": "135703",
            "range": "± 1",
            "category": "proto_run_V03",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86",
            "group": "below_ms"
          },
          {
            "name": "rhr1",
            "unit": "ns/iter",
            "value": "240",
            "range": "± 1",
            "category": "proto_run_V03",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86",
            "group": "below_us"
          },
          {
            "name": "ici3",
            "unit": "ns/iter",
            "value": "15910",
            "range": "± 1",
            "category": "proto_run_V03",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86",
            "group": "below_ms"
          },
          {
            "name": "ihr4",
            "unit": "ns/iter",
            "value": "20528",
            "range": "± 1",
            "category": "proto_run_V03",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86",
            "group": "below_ms"
          },
          {
            "name": "ihi7",
            "unit": "ns/iter",
            "value": "2822649",
            "range": "± 1",
            "category": "proto_run_V03",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86",
            "group": "medium"
          },
          {
            "name": "ici4",
            "unit": "ns/iter",
            "value": "15719",
            "range": "± 1",
            "category": "proto_run_V03",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86",
            "group": "below_ms"
          },
          {
            "name": "rhi5",
            "unit": "ns/iter",
            "value": "87580672",
            "range": "± 1",
            "category": "proto_run_V03",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86",
            "group": "long"
          },
          {
            "name": "rhr5",
            "unit": "ns/iter",
            "value": "3439688",
            "range": "± 1",
            "category": "proto_run_V03",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86",
            "group": "medium"
          },
          {
            "name": "handle_init_conf",
            "unit": "ns/iter",
            "value": "3140060",
            "range": "± 1",
            "category": "proto_run_V03",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86",
            "group": "medium"
          },
          {
            "name": "icr1",
            "unit": "ns/iter",
            "value": "3013915",
            "range": "± 1",
            "category": "proto_run_V03",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86",
            "group": "medium"
          },
          {
            "name": "icr2",
            "unit": "ns/iter",
            "value": "78556",
            "range": "± 1",
            "category": "proto_run_V03",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86",
            "group": "below_ms"
          },
          {
            "name": "icr4",
            "unit": "ns/iter",
            "value": "15800",
            "range": "± 1",
            "category": "proto_run_V03",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86",
            "group": "below_ms"
          },
          {
            "name": "icr7",
            "unit": "ns/iter",
            "value": "13505",
            "range": "± 1",
            "category": "proto_run_V03",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86",
            "group": "below_ms"
          },
          {
            "name": "rhr6",
            "unit": "ns/iter",
            "value": "5633225",
            "range": "± 1",
            "category": "proto_run_V03",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86",
            "group": "medium"
          },
          {
            "name": "handle_resp_conf",
            "unit": "ns/iter",
            "value": "2823169",
            "range": "± 1",
            "category": "proto_run_V03",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86",
            "group": "medium"
          },
          {
            "name": "ihi2",
            "unit": "ns/iter",
            "value": "290",
            "range": "± 1",
            "category": "proto_run_V03",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86",
            "group": "below_us"
          },
          {
            "name": "ihi1",
            "unit": "ns/iter",
            "value": "2904841",
            "range": "± 1",
            "category": "proto_run_V03",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86",
            "group": "medium"
          },
          {
            "name": "rhi7",
            "unit": "ns/iter",
            "value": "15920",
            "range": "± 1",
            "category": "proto_run_V03",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86",
            "group": "below_ms"
          },
          {
            "name": "ici7",
            "unit": "ns/iter",
            "value": "13465",
            "range": "± 1",
            "category": "proto_run_V03",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86",
            "group": "below_ms"
          },
          {
            "name": "rhr3",
            "unit": "ns/iter",
            "value": "15890",
            "range": "± 1",
            "category": "proto_run_V03",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86",
            "group": "below_ms"
          },
          {
            "name": "rhr7",
            "unit": "ns/iter",
            "value": "15829",
            "range": "± 1",
            "category": "proto_run_V03",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86",
            "group": "below_ms"
          },
          {
            "name": "handle_resp_hello",
            "unit": "ns/iter",
            "value": "87803126",
            "range": "± 1",
            "category": "proto_run_V03",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86",
            "group": "long"
          },
          {
            "name": "ihr8",
            "unit": "ns/iter",
            "value": "15850",
            "range": "± 1",
            "category": "proto_run_V03",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86",
            "group": "below_ms"
          },
          {
            "name": "handle_initiation",
            "unit": "ns/iter",
            "value": "12294345",
            "range": "± 1",
            "category": "proto_run_V03",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86",
            "group": "medium"
          }
        ]
      }
    ]
  },
  "groupBy": [
    "os",
    "arch",
    "category",
    "group"
  ],
  "schema": [
    "os",
    "arch",
    "category",
    "group",
    "name"
  ]
}