window.BENCHMARK_DATA = {
  "lastUpdate": 1746024627641,
  "repoUrl": "https://github.com/cryspen/rosenpass",
  "entries": {
    "rosenpass protocol benchmarks": [
      {
        "commit": {
          "author": {
            "email": "jan@cryspen.com",
            "name": "Jan Winkelmann (keks)",
            "username": "keks"
          },
          "committer": {
            "email": "jan@cryspen.com",
            "name": "Jan Winkelmann (keks)",
            "username": "keks"
          },
          "distinct": true,
          "id": "58a58300a4424980411920ab38ea8aaa4835ef05",
          "message": "fix binning in protocol benchmark",
          "timestamp": "2025-04-30T16:42:55+02:00",
          "tree_id": "be22e7023ea3abb29a861bbe7da9d14df4664e8a",
          "url": "https://github.com/cryspen/rosenpass/commit/58a58300a4424980411920ab38ea8aaa4835ef05"
        },
        "date": 1746024320168,
        "bigger_is_better": false,
        "benches": [
          {
            "name": "ihi4",
            "unit": "ns/iter",
            "value": "16140",
            "range": "± 1",
            "category": "proto_run_V02",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86",
            "group": "below_ms"
          },
          {
            "name": "ihr5",
            "unit": "ns/iter",
            "value": "86856176",
            "range": "± 846141",
            "category": "proto_run_V02",
            "sampleSize": "2",
            "os": "linux",
            "arch": "x86",
            "group": "long"
          },
          {
            "name": "icr2",
            "unit": "ns/iter",
            "value": "65953",
            "range": "± 1",
            "category": "proto_run_V02",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86",
            "group": "below_ms"
          },
          {
            "name": "icr3",
            "unit": "ns/iter",
            "value": "14096",
            "range": "± 1",
            "category": "proto_run_V02",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86",
            "group": "below_ms"
          },
          {
            "name": "ihi2",
            "unit": "ns/iter",
            "value": "331",
            "range": "± 1",
            "category": "proto_run_V02",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86",
            "group": "below_us"
          },
          {
            "name": "rhr4",
            "unit": "ns/iter",
            "value": "122067",
            "range": "± 1",
            "category": "proto_run_V02",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86",
            "group": "below_ms"
          },
          {
            "name": "handle_init_hello",
            "unit": "ns/iter",
            "value": "91552705",
            "range": "± 1002312",
            "category": "proto_run_V02",
            "sampleSize": "2",
            "os": "linux",
            "arch": "x86",
            "group": "long"
          },
          {
            "name": "ihi5",
            "unit": "ns/iter",
            "value": "1851830",
            "range": "± 1",
            "category": "proto_run_V02",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86",
            "group": "medium"
          },
          {
            "name": "rhr3",
            "unit": "ns/iter",
            "value": "13916",
            "range": "± 1",
            "category": "proto_run_V02",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86",
            "group": "below_ms"
          },
          {
            "name": "rhr5",
            "unit": "ns/iter",
            "value": "1727218",
            "range": "± 1",
            "category": "proto_run_V02",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86",
            "group": "medium"
          },
          {
            "name": "ici3",
            "unit": "ns/iter",
            "value": "14006",
            "range": "± 1",
            "category": "proto_run_V02",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86",
            "group": "below_ms"
          },
          {
            "name": "icr6",
            "unit": "ns/iter",
            "value": "50",
            "range": "± 1",
            "category": "proto_run_V02",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86",
            "group": "below_us"
          },
          {
            "name": "handle_resp_hello",
            "unit": "ns/iter",
            "value": "86129858",
            "range": "± 1",
            "category": "proto_run_V02",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86",
            "group": "long"
          },
          {
            "name": "ici4",
            "unit": "ns/iter",
            "value": "13906",
            "range": "± 1",
            "category": "proto_run_V02",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86",
            "group": "below_ms"
          },
          {
            "name": "handle_resp_conf",
            "unit": "ns/iter",
            "value": "1127240",
            "range": "± 1",
            "category": "proto_run_V02",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86",
            "group": "medium"
          },
          {
            "name": "ihi3",
            "unit": "ns/iter",
            "value": "83014",
            "range": "± 1",
            "category": "proto_run_V02",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86",
            "group": "below_ms"
          },
          {
            "name": "icr4",
            "unit": "ns/iter",
            "value": "14197",
            "range": "± 1",
            "category": "proto_run_V02",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86",
            "group": "below_ms"
          },
          {
            "name": "ihr6",
            "unit": "ns/iter",
            "value": "15800",
            "range": "± 511",
            "category": "proto_run_V02",
            "sampleSize": "2",
            "os": "linux",
            "arch": "x86",
            "group": "below_ms"
          },
          {
            "name": "handle_init_conf",
            "unit": "ns/iter",
            "value": "2112210",
            "range": "± 701051",
            "category": "proto_run_V02",
            "sampleSize": "2",
            "os": "linux",
            "arch": "x86",
            "group": "medium"
          },
          {
            "name": "handle_initiation",
            "unit": "ns/iter",
            "value": "5694258",
            "range": "± 1",
            "category": "proto_run_V02",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86",
            "group": "medium"
          },
          {
            "name": "rhr1",
            "unit": "ns/iter",
            "value": "241",
            "range": "± 1",
            "category": "proto_run_V02",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86",
            "group": "below_us"
          },
          {
            "name": "rhi3",
            "unit": "ns/iter",
            "value": "13986",
            "range": "± 1",
            "category": "proto_run_V02",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86",
            "group": "below_ms"
          },
          {
            "name": "ihr8",
            "unit": "ns/iter",
            "value": "14136",
            "range": "± 1",
            "category": "proto_run_V02",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86",
            "group": "below_ms"
          },
          {
            "name": "ihr1",
            "unit": "ns/iter",
            "value": "1967265",
            "range": "± 843291",
            "category": "proto_run_V02",
            "sampleSize": "2",
            "os": "linux",
            "arch": "x86",
            "group": "medium"
          },
          {
            "name": "ihr4",
            "unit": "ns/iter",
            "value": "18209",
            "range": "± 2420",
            "category": "proto_run_V02",
            "sampleSize": "2",
            "os": "linux",
            "arch": "x86",
            "group": "below_ms"
          },
          {
            "name": "rhi6",
            "unit": "ns/iter",
            "value": "7163",
            "range": "± 1",
            "category": "proto_run_V02",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86",
            "group": "below_ms"
          },
          {
            "name": "ihr7",
            "unit": "ns/iter",
            "value": "1134544",
            "range": "± 1",
            "category": "proto_run_V02",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86",
            "group": "medium"
          },
          {
            "name": "ihi6",
            "unit": "ns/iter",
            "value": "1149702",
            "range": "± 1",
            "category": "proto_run_V02",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86",
            "group": "medium"
          },
          {
            "name": "rhi7",
            "unit": "ns/iter",
            "value": "14156",
            "range": "± 1",
            "category": "proto_run_V02",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86",
            "group": "below_ms"
          },
          {
            "name": "rhr6",
            "unit": "ns/iter",
            "value": "2362341",
            "range": "± 1",
            "category": "proto_run_V02",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86",
            "group": "medium"
          },
          {
            "name": "ihi8",
            "unit": "ns/iter",
            "value": "14137",
            "range": "± 1",
            "category": "proto_run_V02",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86",
            "group": "below_ms"
          },
          {
            "name": "rhi5",
            "unit": "ns/iter",
            "value": "85927741",
            "range": "± 1",
            "category": "proto_run_V02",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86",
            "group": "long"
          },
          {
            "name": "rhi4",
            "unit": "ns/iter",
            "value": "121917",
            "range": "± 1",
            "category": "proto_run_V02",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86",
            "group": "below_ms"
          },
          {
            "name": "icr1",
            "unit": "ns/iter",
            "value": "2057893",
            "range": "± 755266",
            "category": "proto_run_V02",
            "sampleSize": "2",
            "os": "linux",
            "arch": "x86",
            "group": "medium"
          },
          {
            "name": "ihi7",
            "unit": "ns/iter",
            "value": "1140044",
            "range": "± 1",
            "category": "proto_run_V02",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86",
            "group": "medium"
          },
          {
            "name": "icr7",
            "unit": "ns/iter",
            "value": "12223",
            "range": "± 1",
            "category": "proto_run_V02",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86",
            "group": "below_ms"
          },
          {
            "name": "rhr7",
            "unit": "ns/iter",
            "value": "14157",
            "range": "± 1",
            "category": "proto_run_V02",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86",
            "group": "below_ms"
          },
          {
            "name": "ihi1",
            "unit": "ns/iter",
            "value": "1263604",
            "range": "± 1",
            "category": "proto_run_V02",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86",
            "group": "medium"
          },
          {
            "name": "ici7",
            "unit": "ns/iter",
            "value": "12093",
            "range": "± 1",
            "category": "proto_run_V02",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86",
            "group": "below_ms"
          },
          {
            "name": "icr3",
            "unit": "ns/iter",
            "value": "16021",
            "range": "± 1",
            "category": "proto_run_V03",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86",
            "group": "below_ms"
          },
          {
            "name": "ihr1",
            "unit": "ns/iter",
            "value": "2817068",
            "range": "± 1",
            "category": "proto_run_V03",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86",
            "group": "medium"
          },
          {
            "name": "ihr5",
            "unit": "ns/iter",
            "value": "87670167",
            "range": "± 1",
            "category": "proto_run_V03",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86",
            "group": "long"
          },
          {
            "name": "rhi3",
            "unit": "ns/iter",
            "value": "15909",
            "range": "± 1",
            "category": "proto_run_V03",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86",
            "group": "below_ms"
          },
          {
            "name": "rhr4",
            "unit": "ns/iter",
            "value": "134531",
            "range": "± 1",
            "category": "proto_run_V03",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86",
            "group": "below_ms"
          },
          {
            "name": "ihi4",
            "unit": "ns/iter",
            "value": "21009",
            "range": "± 1",
            "category": "proto_run_V03",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86",
            "group": "below_ms"
          },
          {
            "name": "rhi6",
            "unit": "ns/iter",
            "value": "8726",
            "range": "± 1",
            "category": "proto_run_V03",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86",
            "group": "below_ms"
          },
          {
            "name": "ihi3",
            "unit": "ns/iter",
            "value": "79639",
            "range": "± 1",
            "category": "proto_run_V03",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86",
            "group": "below_ms"
          },
          {
            "name": "icr6",
            "unit": "ns/iter",
            "value": "131",
            "range": "± 1",
            "category": "proto_run_V03",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86",
            "group": "below_us"
          },
          {
            "name": "ihr7",
            "unit": "ns/iter",
            "value": "2828219",
            "range": "± 1",
            "category": "proto_run_V03",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86",
            "group": "medium"
          },
          {
            "name": "ihi5",
            "unit": "ns/iter",
            "value": "3504579",
            "range": "± 1",
            "category": "proto_run_V03",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86",
            "group": "medium"
          },
          {
            "name": "handle_init_hello",
            "unit": "ns/iter",
            "value": "102609909",
            "range": "± 1",
            "category": "proto_run_V03",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86",
            "group": "long"
          },
          {
            "name": "ihi8",
            "unit": "ns/iter",
            "value": "15859",
            "range": "± 1",
            "category": "proto_run_V03",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86",
            "group": "below_ms"
          },
          {
            "name": "ihr6",
            "unit": "ns/iter",
            "value": "17453",
            "range": "± 1",
            "category": "proto_run_V03",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86",
            "group": "below_ms"
          },
          {
            "name": "ihi6",
            "unit": "ns/iter",
            "value": "2844149",
            "range": "± 1",
            "category": "proto_run_V03",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86",
            "group": "medium"
          },
          {
            "name": "rhi4",
            "unit": "ns/iter",
            "value": "135703",
            "range": "± 1",
            "category": "proto_run_V03",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86",
            "group": "below_ms"
          },
          {
            "name": "rhr1",
            "unit": "ns/iter",
            "value": "240",
            "range": "± 1",
            "category": "proto_run_V03",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86",
            "group": "below_us"
          },
          {
            "name": "ici3",
            "unit": "ns/iter",
            "value": "15910",
            "range": "± 1",
            "category": "proto_run_V03",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86",
            "group": "below_ms"
          },
          {
            "name": "ihr4",
            "unit": "ns/iter",
            "value": "20528",
            "range": "± 1",
            "category": "proto_run_V03",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86",
            "group": "below_ms"
          },
          {
            "name": "ihi7",
            "unit": "ns/iter",
            "value": "2822649",
            "range": "± 1",
            "category": "proto_run_V03",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86",
            "group": "medium"
          },
          {
            "name": "ici4",
            "unit": "ns/iter",
            "value": "15719",
            "range": "± 1",
            "category": "proto_run_V03",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86",
            "group": "below_ms"
          },
          {
            "name": "rhi5",
            "unit": "ns/iter",
            "value": "87580672",
            "range": "± 1",
            "category": "proto_run_V03",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86",
            "group": "long"
          },
          {
            "name": "rhr5",
            "unit": "ns/iter",
            "value": "3439688",
            "range": "± 1",
            "category": "proto_run_V03",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86",
            "group": "medium"
          },
          {
            "name": "handle_init_conf",
            "unit": "ns/iter",
            "value": "3140060",
            "range": "± 1",
            "category": "proto_run_V03",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86",
            "group": "medium"
          },
          {
            "name": "icr1",
            "unit": "ns/iter",
            "value": "3013915",
            "range": "± 1",
            "category": "proto_run_V03",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86",
            "group": "medium"
          },
          {
            "name": "icr2",
            "unit": "ns/iter",
            "value": "78556",
            "range": "± 1",
            "category": "proto_run_V03",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86",
            "group": "below_ms"
          },
          {
            "name": "icr4",
            "unit": "ns/iter",
            "value": "15800",
            "range": "± 1",
            "category": "proto_run_V03",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86",
            "group": "below_ms"
          },
          {
            "name": "icr7",
            "unit": "ns/iter",
            "value": "13505",
            "range": "± 1",
            "category": "proto_run_V03",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86",
            "group": "below_ms"
          },
          {
            "name": "rhr6",
            "unit": "ns/iter",
            "value": "5633225",
            "range": "± 1",
            "category": "proto_run_V03",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86",
            "group": "medium"
          },
          {
            "name": "handle_resp_conf",
            "unit": "ns/iter",
            "value": "2823169",
            "range": "± 1",
            "category": "proto_run_V03",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86",
            "group": "medium"
          },
          {
            "name": "ihi2",
            "unit": "ns/iter",
            "value": "290",
            "range": "± 1",
            "category": "proto_run_V03",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86",
            "group": "below_us"
          },
          {
            "name": "ihi1",
            "unit": "ns/iter",
            "value": "2904841",
            "range": "± 1",
            "category": "proto_run_V03",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86",
            "group": "medium"
          },
          {
            "name": "rhi7",
            "unit": "ns/iter",
            "value": "15920",
            "range": "± 1",
            "category": "proto_run_V03",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86",
            "group": "below_ms"
          },
          {
            "name": "ici7",
            "unit": "ns/iter",
            "value": "13465",
            "range": "± 1",
            "category": "proto_run_V03",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86",
            "group": "below_ms"
          },
          {
            "name": "rhr3",
            "unit": "ns/iter",
            "value": "15890",
            "range": "± 1",
            "category": "proto_run_V03",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86",
            "group": "below_ms"
          },
          {
            "name": "rhr7",
            "unit": "ns/iter",
            "value": "15829",
            "range": "± 1",
            "category": "proto_run_V03",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86",
            "group": "below_ms"
          },
          {
            "name": "handle_resp_hello",
            "unit": "ns/iter",
            "value": "87803126",
            "range": "± 1",
            "category": "proto_run_V03",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86",
            "group": "long"
          },
          {
            "name": "ihr8",
            "unit": "ns/iter",
            "value": "15850",
            "range": "± 1",
            "category": "proto_run_V03",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86",
            "group": "below_ms"
          },
          {
            "name": "handle_initiation",
            "unit": "ns/iter",
            "value": "12294345",
            "range": "± 1",
            "category": "proto_run_V03",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86",
            "group": "medium"
          }
        ]
      },
      {
        "commit": {
          "author": {
            "email": "jan@cryspen.com",
            "name": "Jan Winkelmann (keks)",
            "username": "keks"
          },
          "committer": {
            "email": "jan@cryspen.com",
            "name": "Jan Winkelmann (keks)",
            "username": "keks"
          },
          "distinct": true,
          "id": "58a58300a4424980411920ab38ea8aaa4835ef05",
          "message": "fix binning in protocol benchmark",
          "timestamp": "2025-04-30T16:42:55+02:00",
          "tree_id": "be22e7023ea3abb29a861bbe7da9d14df4664e8a",
          "url": "https://github.com/cryspen/rosenpass/commit/58a58300a4424980411920ab38ea8aaa4835ef05"
        },
        "date": 1746024330210,
        "bigger_is_better": false,
        "benches": [
          {
            "name": "icr7",
            "unit": "ns/iter",
            "value": "6743",
            "range": "± 1",
            "category": "proto_run_V02",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86_64",
            "group": "below_ms"
          },
          {
            "name": "ihi7",
            "unit": "ns/iter",
            "value": "534685",
            "range": "± 1",
            "category": "proto_run_V02",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86_64",
            "group": "medium"
          },
          {
            "name": "ici3",
            "unit": "ns/iter",
            "value": "7724",
            "range": "± 1",
            "category": "proto_run_V02",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86_64",
            "group": "below_ms"
          },
          {
            "name": "ici7",
            "unit": "ns/iter",
            "value": "6843",
            "range": "± 1",
            "category": "proto_run_V02",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86_64",
            "group": "below_ms"
          },
          {
            "name": "ihi4",
            "unit": "ns/iter",
            "value": "9277",
            "range": "± 1",
            "category": "proto_run_V02",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86_64",
            "group": "below_ms"
          },
          {
            "name": "handle_resp_hello",
            "unit": "ns/iter",
            "value": "713389",
            "range": "± 1",
            "category": "proto_run_V02",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86_64",
            "group": "long"
          },
          {
            "name": "icr2",
            "unit": "ns/iter",
            "value": "59952",
            "range": "± 1",
            "category": "proto_run_V02",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86_64",
            "group": "below_ms"
          },
          {
            "name": "rhi4",
            "unit": "ns/iter",
            "value": "24756",
            "range": "± 1",
            "category": "proto_run_V02",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86_64",
            "group": "below_ms"
          },
          {
            "name": "ihi1",
            "unit": "ns/iter",
            "value": "615916",
            "range": "± 1",
            "category": "proto_run_V02",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86_64",
            "group": "medium"
          },
          {
            "name": "ihi3",
            "unit": "ns/iter",
            "value": "17072",
            "range": "± 1",
            "category": "proto_run_V02",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86_64",
            "group": "below_ms"
          },
          {
            "name": "ihi2",
            "unit": "ns/iter",
            "value": "270",
            "range": "± 1",
            "category": "proto_run_V02",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86_64",
            "group": "below_us"
          },
          {
            "name": "icr3",
            "unit": "ns/iter",
            "value": "7985",
            "range": "± 1",
            "category": "proto_run_V02",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86_64",
            "group": "below_ms"
          },
          {
            "name": "icr6",
            "unit": "ns/iter",
            "value": "50",
            "range": "± 1",
            "category": "proto_run_V02",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86_64",
            "group": "below_us"
          },
          {
            "name": "ihr8",
            "unit": "ns/iter",
            "value": "8266",
            "range": "± 1",
            "category": "proto_run_V02",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86_64",
            "group": "below_ms"
          },
          {
            "name": "rhi7",
            "unit": "ns/iter",
            "value": "8366",
            "range": "± 1",
            "category": "proto_run_V02",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86_64",
            "group": "below_ms"
          },
          {
            "name": "rhr7",
            "unit": "ns/iter",
            "value": "8356",
            "range": "± 1",
            "category": "proto_run_V02",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86_64",
            "group": "below_ms"
          },
          {
            "name": "handle_initiation",
            "unit": "ns/iter",
            "value": "2505454",
            "range": "± 1",
            "category": "proto_run_V02",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86_64",
            "group": "medium"
          },
          {
            "name": "ici4",
            "unit": "ns/iter",
            "value": "8226",
            "range": "± 1",
            "category": "proto_run_V02",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86_64",
            "group": "below_ms"
          },
          {
            "name": "handle_init_conf",
            "unit": "ns/iter",
            "value": "1138725",
            "range": "± 346820",
            "category": "proto_run_V02",
            "sampleSize": "2",
            "os": "linux",
            "arch": "x86_64",
            "group": "medium"
          },
          {
            "name": "handle_resp_conf",
            "unit": "ns/iter",
            "value": "522062",
            "range": "± 1",
            "category": "proto_run_V02",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86_64",
            "group": "medium"
          },
          {
            "name": "rhr6",
            "unit": "ns/iter",
            "value": "1119374",
            "range": "± 1",
            "category": "proto_run_V02",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86_64",
            "group": "medium"
          },
          {
            "name": "rhi6",
            "unit": "ns/iter",
            "value": "3937",
            "range": "± 1",
            "category": "proto_run_V02",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86_64",
            "group": "below_ms"
          },
          {
            "name": "rhr1",
            "unit": "ns/iter",
            "value": "260",
            "range": "± 1",
            "category": "proto_run_V02",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86_64",
            "group": "below_us"
          },
          {
            "name": "rhi3",
            "unit": "ns/iter",
            "value": "7855",
            "range": "± 1",
            "category": "proto_run_V02",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86_64",
            "group": "below_ms"
          },
          {
            "name": "rhr4",
            "unit": "ns/iter",
            "value": "28593",
            "range": "± 1",
            "category": "proto_run_V02",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86_64",
            "group": "below_ms"
          },
          {
            "name": "ihr4",
            "unit": "ns/iter",
            "value": "9813",
            "range": "± 1187",
            "category": "proto_run_V02",
            "sampleSize": "2",
            "os": "linux",
            "arch": "x86_64",
            "group": "below_ms"
          },
          {
            "name": "ihr5",
            "unit": "ns/iter",
            "value": "1147722",
            "range": "± 502641",
            "category": "proto_run_V02",
            "sampleSize": "2",
            "os": "linux",
            "arch": "x86_64",
            "group": "long"
          },
          {
            "name": "rhr3",
            "unit": "ns/iter",
            "value": "7805",
            "range": "± 1",
            "category": "proto_run_V02",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86_64",
            "group": "below_ms"
          },
          {
            "name": "handle_init_hello",
            "unit": "ns/iter",
            "value": "3304507",
            "range": "± 163319",
            "category": "proto_run_V02",
            "sampleSize": "2",
            "os": "linux",
            "arch": "x86_64",
            "group": "long"
          },
          {
            "name": "icr1",
            "unit": "ns/iter",
            "value": "1096066",
            "range": "± 389380",
            "category": "proto_run_V02",
            "sampleSize": "2",
            "os": "linux",
            "arch": "x86_64",
            "group": "medium"
          },
          {
            "name": "ihr1",
            "unit": "ns/iter",
            "value": "995193",
            "range": "± 476297",
            "category": "proto_run_V02",
            "sampleSize": "2",
            "os": "linux",
            "arch": "x86_64",
            "group": "medium"
          },
          {
            "name": "icr4",
            "unit": "ns/iter",
            "value": "8586",
            "range": "± 1",
            "category": "proto_run_V02",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86_64",
            "group": "below_ms"
          },
          {
            "name": "rhi5",
            "unit": "ns/iter",
            "value": "644740",
            "range": "± 1",
            "category": "proto_run_V02",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86_64",
            "group": "long"
          },
          {
            "name": "ihi6",
            "unit": "ns/iter",
            "value": "553000",
            "range": "± 1",
            "category": "proto_run_V02",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86_64",
            "group": "medium"
          },
          {
            "name": "ihi5",
            "unit": "ns/iter",
            "value": "630715",
            "range": "± 1",
            "category": "proto_run_V02",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86_64",
            "group": "medium"
          },
          {
            "name": "ihr6",
            "unit": "ns/iter",
            "value": "8290",
            "range": "± 466",
            "category": "proto_run_V02",
            "sampleSize": "2",
            "os": "linux",
            "arch": "x86_64",
            "group": "below_ms"
          },
          {
            "name": "ihr7",
            "unit": "ns/iter",
            "value": "549693",
            "range": "± 1",
            "category": "proto_run_V02",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86_64",
            "group": "medium"
          },
          {
            "name": "rhr5",
            "unit": "ns/iter",
            "value": "560063",
            "range": "± 1",
            "category": "proto_run_V02",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86_64",
            "group": "medium"
          },
          {
            "name": "ihi8",
            "unit": "ns/iter",
            "value": "8496",
            "range": "± 1",
            "category": "proto_run_V02",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86_64",
            "group": "below_ms"
          },
          {
            "name": "ihr1",
            "unit": "ns/iter",
            "value": "1483643",
            "range": "± 1",
            "category": "proto_run_V03",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86_64",
            "group": "medium"
          },
          {
            "name": "ihr4",
            "unit": "ns/iter",
            "value": "10920",
            "range": "± 1",
            "category": "proto_run_V03",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86_64",
            "group": "below_ms"
          },
          {
            "name": "icr4",
            "unit": "ns/iter",
            "value": "9287",
            "range": "± 1",
            "category": "proto_run_V03",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86_64",
            "group": "below_ms"
          },
          {
            "name": "handle_resp_hello",
            "unit": "ns/iter",
            "value": "1676421",
            "range": "± 1",
            "category": "proto_run_V03",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86_64",
            "group": "long"
          },
          {
            "name": "icr3",
            "unit": "ns/iter",
            "value": "8606",
            "range": "± 1",
            "category": "proto_run_V03",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86_64",
            "group": "below_ms"
          },
          {
            "name": "rhi5",
            "unit": "ns/iter",
            "value": "1600620",
            "range": "± 1",
            "category": "proto_run_V03",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86_64",
            "group": "long"
          },
          {
            "name": "ihi5",
            "unit": "ns/iter",
            "value": "1619345",
            "range": "± 1",
            "category": "proto_run_V03",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86_64",
            "group": "medium"
          },
          {
            "name": "rhr3",
            "unit": "ns/iter",
            "value": "8506",
            "range": "± 1",
            "category": "proto_run_V03",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86_64",
            "group": "below_ms"
          },
          {
            "name": "rhi3",
            "unit": "ns/iter",
            "value": "8706",
            "range": "± 1",
            "category": "proto_run_V03",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86_64",
            "group": "below_ms"
          },
          {
            "name": "ici4",
            "unit": "ns/iter",
            "value": "9037",
            "range": "± 1",
            "category": "proto_run_V03",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86_64",
            "group": "below_ms"
          },
          {
            "name": "ihr7",
            "unit": "ns/iter",
            "value": "1492328",
            "range": "± 1",
            "category": "proto_run_V03",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86_64",
            "group": "medium"
          },
          {
            "name": "ihi4",
            "unit": "ns/iter",
            "value": "11321",
            "range": "± 1",
            "category": "proto_run_V03",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86_64",
            "group": "below_ms"
          },
          {
            "name": "ihr5",
            "unit": "ns/iter",
            "value": "1652236",
            "range": "± 1",
            "category": "proto_run_V03",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86_64",
            "group": "long"
          },
          {
            "name": "ihi3",
            "unit": "ns/iter",
            "value": "12954",
            "range": "± 1",
            "category": "proto_run_V03",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86_64",
            "group": "below_ms"
          },
          {
            "name": "icr7",
            "unit": "ns/iter",
            "value": "7334",
            "range": "± 1",
            "category": "proto_run_V03",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86_64",
            "group": "below_ms"
          },
          {
            "name": "ihi6",
            "unit": "ns/iter",
            "value": "1486949",
            "range": "± 1",
            "category": "proto_run_V03",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86_64",
            "group": "medium"
          },
          {
            "name": "ihi8",
            "unit": "ns/iter",
            "value": "9237",
            "range": "± 1",
            "category": "proto_run_V03",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86_64",
            "group": "below_ms"
          },
          {
            "name": "rhr1",
            "unit": "ns/iter",
            "value": "220",
            "range": "± 1",
            "category": "proto_run_V03",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86_64",
            "group": "below_us"
          },
          {
            "name": "ihr6",
            "unit": "ns/iter",
            "value": "9898",
            "range": "± 1",
            "category": "proto_run_V03",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86_64",
            "group": "below_ms"
          },
          {
            "name": "rhi6",
            "unit": "ns/iter",
            "value": "4699",
            "range": "± 1",
            "category": "proto_run_V03",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86_64",
            "group": "below_ms"
          },
          {
            "name": "rhi4",
            "unit": "ns/iter",
            "value": "27732",
            "range": "± 1",
            "category": "proto_run_V03",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86_64",
            "group": "below_ms"
          },
          {
            "name": "ihi7",
            "unit": "ns/iter",
            "value": "1510723",
            "range": "± 1",
            "category": "proto_run_V03",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86_64",
            "group": "medium"
          },
          {
            "name": "rhr4",
            "unit": "ns/iter",
            "value": "38171",
            "range": "± 1",
            "category": "proto_run_V03",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86_64",
            "group": "below_ms"
          },
          {
            "name": "icr2",
            "unit": "ns/iter",
            "value": "54942",
            "range": "± 1",
            "category": "proto_run_V03",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86_64",
            "group": "below_ms"
          },
          {
            "name": "ici3",
            "unit": "ns/iter",
            "value": "8436",
            "range": "± 1",
            "category": "proto_run_V03",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86_64",
            "group": "below_ms"
          },
          {
            "name": "ihi1",
            "unit": "ns/iter",
            "value": "1596953",
            "range": "± 1",
            "category": "proto_run_V03",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86_64",
            "group": "medium"
          },
          {
            "name": "handle_init_hello",
            "unit": "ns/iter",
            "value": "9224505",
            "range": "± 1",
            "category": "proto_run_V03",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86_64",
            "group": "long"
          },
          {
            "name": "ihi2",
            "unit": "ns/iter",
            "value": "201",
            "range": "± 1",
            "category": "proto_run_V03",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86_64",
            "group": "below_us"
          },
          {
            "name": "rhr6",
            "unit": "ns/iter",
            "value": "2985249",
            "range": "± 1",
            "category": "proto_run_V03",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86_64",
            "group": "medium"
          },
          {
            "name": "rhr7",
            "unit": "ns/iter",
            "value": "9107",
            "range": "± 1",
            "category": "proto_run_V03",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86_64",
            "group": "below_ms"
          },
          {
            "name": "handle_init_conf",
            "unit": "ns/iter",
            "value": "1752382",
            "range": "± 1",
            "category": "proto_run_V03",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86_64",
            "group": "medium"
          },
          {
            "name": "rhi7",
            "unit": "ns/iter",
            "value": "9177",
            "range": "± 1",
            "category": "proto_run_V03",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86_64",
            "group": "below_ms"
          },
          {
            "name": "rhr5",
            "unit": "ns/iter",
            "value": "1524348",
            "range": "± 1",
            "category": "proto_run_V03",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86_64",
            "group": "medium"
          },
          {
            "name": "icr1",
            "unit": "ns/iter",
            "value": "1670250",
            "range": "± 1",
            "category": "proto_run_V03",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86_64",
            "group": "medium"
          },
          {
            "name": "handle_initiation",
            "unit": "ns/iter",
            "value": "6339694",
            "range": "± 1",
            "category": "proto_run_V03",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86_64",
            "group": "medium"
          },
          {
            "name": "icr6",
            "unit": "ns/iter",
            "value": "40",
            "range": "± 1",
            "category": "proto_run_V03",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86_64",
            "group": "below_us"
          },
          {
            "name": "ici7",
            "unit": "ns/iter",
            "value": "7273",
            "range": "± 1",
            "category": "proto_run_V03",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86_64",
            "group": "below_ms"
          },
          {
            "name": "ihr8",
            "unit": "ns/iter",
            "value": "9047",
            "range": "± 1",
            "category": "proto_run_V03",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86_64",
            "group": "below_ms"
          },
          {
            "name": "handle_resp_conf",
            "unit": "ns/iter",
            "value": "1474635",
            "range": "± 1",
            "category": "proto_run_V03",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86_64",
            "group": "medium"
          }
        ]
      },
      {
        "commit": {
          "author": {
            "email": "jan@cryspen.com",
            "name": "Jan Winkelmann (keks)",
            "username": "keks"
          },
          "committer": {
            "email": "jan@cryspen.com",
            "name": "Jan Winkelmann (keks)",
            "username": "keks"
          },
          "distinct": true,
          "id": "58a58300a4424980411920ab38ea8aaa4835ef05",
          "message": "fix binning in protocol benchmark",
          "timestamp": "2025-04-30T16:42:55+02:00",
          "tree_id": "be22e7023ea3abb29a861bbe7da9d14df4664e8a",
          "url": "https://github.com/cryspen/rosenpass/commit/58a58300a4424980411920ab38ea8aaa4835ef05"
        },
        "date": 1746024626668,
        "bigger_is_better": false,
        "benches": [
          {
            "name": "rhr3",
            "unit": "ns/iter",
            "value": "14057",
            "range": "± 1",
            "category": "proto_run_V02",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86",
            "group": "below_ms"
          },
          {
            "name": "ihi1",
            "unit": "ns/iter",
            "value": "1247580",
            "range": "± 1",
            "category": "proto_run_V02",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86",
            "group": "medium"
          },
          {
            "name": "handle_init_conf",
            "unit": "ns/iter",
            "value": "2142627",
            "range": "± 670988",
            "category": "proto_run_V02",
            "sampleSize": "2",
            "os": "linux",
            "arch": "x86",
            "group": "medium"
          },
          {
            "name": "ihi7",
            "unit": "ns/iter",
            "value": "1149617",
            "range": "± 1",
            "category": "proto_run_V02",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86",
            "group": "medium"
          },
          {
            "name": "ihr8",
            "unit": "ns/iter",
            "value": "14077",
            "range": "± 1",
            "category": "proto_run_V02",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86",
            "group": "below_ms"
          },
          {
            "name": "rhi5",
            "unit": "ns/iter",
            "value": "85981690",
            "range": "± 1",
            "category": "proto_run_V02",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86",
            "group": "long"
          },
          {
            "name": "handle_resp_conf",
            "unit": "ns/iter",
            "value": "1135812",
            "range": "± 1",
            "category": "proto_run_V02",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86",
            "group": "medium"
          },
          {
            "name": "rhr5",
            "unit": "ns/iter",
            "value": "1772711",
            "range": "± 1",
            "category": "proto_run_V02",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86",
            "group": "medium"
          },
          {
            "name": "icr2",
            "unit": "ns/iter",
            "value": "86001",
            "range": "± 1",
            "category": "proto_run_V02",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86",
            "group": "below_ms"
          },
          {
            "name": "handle_resp_hello",
            "unit": "ns/iter",
            "value": "86199416",
            "range": "± 1",
            "category": "proto_run_V02",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86",
            "group": "long"
          },
          {
            "name": "icr7",
            "unit": "ns/iter",
            "value": "12323",
            "range": "± 1",
            "category": "proto_run_V02",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86",
            "group": "below_ms"
          },
          {
            "name": "ici4",
            "unit": "ns/iter",
            "value": "14217",
            "range": "± 1",
            "category": "proto_run_V02",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86",
            "group": "below_ms"
          },
          {
            "name": "rhi4",
            "unit": "ns/iter",
            "value": "121347",
            "range": "± 1",
            "category": "proto_run_V02",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86",
            "group": "below_ms"
          },
          {
            "name": "ihr5",
            "unit": "ns/iter",
            "value": "87290811",
            "range": "± 1316635",
            "category": "proto_run_V02",
            "sampleSize": "2",
            "os": "linux",
            "arch": "x86",
            "group": "long"
          },
          {
            "name": "ihi8",
            "unit": "ns/iter",
            "value": "14166",
            "range": "± 1",
            "category": "proto_run_V02",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86",
            "group": "below_ms"
          },
          {
            "name": "rhi6",
            "unit": "ns/iter",
            "value": "7414",
            "range": "± 1",
            "category": "proto_run_V02",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86",
            "group": "below_ms"
          },
          {
            "name": "ihi6",
            "unit": "ns/iter",
            "value": "1144788",
            "range": "± 1",
            "category": "proto_run_V02",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86",
            "group": "medium"
          },
          {
            "name": "rhr4",
            "unit": "ns/iter",
            "value": "123921",
            "range": "± 1",
            "category": "proto_run_V02",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86",
            "group": "below_ms"
          },
          {
            "name": "ihr6",
            "unit": "ns/iter",
            "value": "16200",
            "range": "± 791",
            "category": "proto_run_V02",
            "sampleSize": "2",
            "os": "linux",
            "arch": "x86",
            "group": "below_ms"
          },
          {
            "name": "rhi7",
            "unit": "ns/iter",
            "value": "17492",
            "range": "± 1",
            "category": "proto_run_V02",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86",
            "group": "below_ms"
          },
          {
            "name": "handle_init_hello",
            "unit": "ns/iter",
            "value": "92133742",
            "range": "± 478764",
            "category": "proto_run_V02",
            "sampleSize": "2",
            "os": "linux",
            "arch": "x86",
            "group": "long"
          },
          {
            "name": "ihi4",
            "unit": "ns/iter",
            "value": "16059",
            "range": "± 1",
            "category": "proto_run_V02",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86",
            "group": "below_ms"
          },
          {
            "name": "ihr7",
            "unit": "ns/iter",
            "value": "1133708",
            "range": "± 1",
            "category": "proto_run_V02",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86",
            "group": "medium"
          },
          {
            "name": "ihr1",
            "unit": "ns/iter",
            "value": "2068048",
            "range": "± 942516",
            "category": "proto_run_V02",
            "sampleSize": "2",
            "os": "linux",
            "arch": "x86",
            "group": "medium"
          },
          {
            "name": "icr6",
            "unit": "ns/iter",
            "value": "50",
            "range": "± 1",
            "category": "proto_run_V02",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86",
            "group": "below_us"
          },
          {
            "name": "rhr1",
            "unit": "ns/iter",
            "value": "881",
            "range": "± 1",
            "category": "proto_run_V02",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86",
            "group": "below_us"
          },
          {
            "name": "ihr4",
            "unit": "ns/iter",
            "value": "27511",
            "range": "± 6823",
            "category": "proto_run_V02",
            "sampleSize": "2",
            "os": "linux",
            "arch": "x86",
            "group": "below_ms"
          },
          {
            "name": "rhr6",
            "unit": "ns/iter",
            "value": "2386177",
            "range": "± 1",
            "category": "proto_run_V02",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86",
            "group": "medium"
          },
          {
            "name": "ihi3",
            "unit": "ns/iter",
            "value": "84919",
            "range": "± 1",
            "category": "proto_run_V02",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86",
            "group": "below_ms"
          },
          {
            "name": "rhi3",
            "unit": "ns/iter",
            "value": "14016",
            "range": "± 1",
            "category": "proto_run_V02",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86",
            "group": "below_ms"
          },
          {
            "name": "icr1",
            "unit": "ns/iter",
            "value": "2078277",
            "range": "± 735218",
            "category": "proto_run_V02",
            "sampleSize": "2",
            "os": "linux",
            "arch": "x86",
            "group": "medium"
          },
          {
            "name": "icr3",
            "unit": "ns/iter",
            "value": "13986",
            "range": "± 1",
            "category": "proto_run_V02",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86",
            "group": "below_ms"
          },
          {
            "name": "icr4",
            "unit": "ns/iter",
            "value": "14197",
            "range": "± 1",
            "category": "proto_run_V02",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86",
            "group": "below_ms"
          },
          {
            "name": "ici3",
            "unit": "ns/iter",
            "value": "16891",
            "range": "± 1",
            "category": "proto_run_V02",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86",
            "group": "below_ms"
          },
          {
            "name": "handle_initiation",
            "unit": "ns/iter",
            "value": "5643702",
            "range": "± 1",
            "category": "proto_run_V02",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86",
            "group": "medium"
          },
          {
            "name": "ici7",
            "unit": "ns/iter",
            "value": "12463",
            "range": "± 1",
            "category": "proto_run_V02",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86",
            "group": "below_ms"
          },
          {
            "name": "ihi2",
            "unit": "ns/iter",
            "value": "331",
            "range": "± 1",
            "category": "proto_run_V02",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86",
            "group": "below_us"
          },
          {
            "name": "ihi5",
            "unit": "ns/iter",
            "value": "1829768",
            "range": "± 1",
            "category": "proto_run_V02",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86",
            "group": "medium"
          },
          {
            "name": "rhr7",
            "unit": "ns/iter",
            "value": "14176",
            "range": "± 1",
            "category": "proto_run_V02",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86",
            "group": "below_ms"
          },
          {
            "name": "rhi5",
            "unit": "ns/iter",
            "value": "87682877",
            "range": "± 1",
            "category": "proto_run_V03",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86",
            "group": "long"
          },
          {
            "name": "rhr3",
            "unit": "ns/iter",
            "value": "15920",
            "range": "± 1",
            "category": "proto_run_V03",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86",
            "group": "below_ms"
          },
          {
            "name": "ihi3",
            "unit": "ns/iter",
            "value": "87524",
            "range": "± 1",
            "category": "proto_run_V03",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86",
            "group": "below_ms"
          },
          {
            "name": "ici7",
            "unit": "ns/iter",
            "value": "14136",
            "range": "± 1",
            "category": "proto_run_V03",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86",
            "group": "below_ms"
          },
          {
            "name": "icr4",
            "unit": "ns/iter",
            "value": "15960",
            "range": "± 1",
            "category": "proto_run_V03",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86",
            "group": "below_ms"
          },
          {
            "name": "rhr1",
            "unit": "ns/iter",
            "value": "621",
            "range": "± 1",
            "category": "proto_run_V03",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86",
            "group": "below_us"
          },
          {
            "name": "icr3",
            "unit": "ns/iter",
            "value": "16150",
            "range": "± 1",
            "category": "proto_run_V03",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86",
            "group": "below_ms"
          },
          {
            "name": "icr6",
            "unit": "ns/iter",
            "value": "60",
            "range": "± 1",
            "category": "proto_run_V03",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86",
            "group": "below_us"
          },
          {
            "name": "icr7",
            "unit": "ns/iter",
            "value": "13786",
            "range": "± 1",
            "category": "proto_run_V03",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86",
            "group": "below_ms"
          },
          {
            "name": "ihr1",
            "unit": "ns/iter",
            "value": "2809438",
            "range": "± 1",
            "category": "proto_run_V03",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86",
            "group": "medium"
          },
          {
            "name": "ihi1",
            "unit": "ns/iter",
            "value": "2917059",
            "range": "± 1",
            "category": "proto_run_V03",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86",
            "group": "medium"
          },
          {
            "name": "ihr8",
            "unit": "ns/iter",
            "value": "15790",
            "range": "± 1",
            "category": "proto_run_V03",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86",
            "group": "below_ms"
          },
          {
            "name": "rhi6",
            "unit": "ns/iter",
            "value": "8826",
            "range": "± 1",
            "category": "proto_run_V03",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86",
            "group": "below_ms"
          },
          {
            "name": "icr1",
            "unit": "ns/iter",
            "value": "3047873",
            "range": "± 1",
            "category": "proto_run_V03",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86",
            "group": "medium"
          },
          {
            "name": "rhi4",
            "unit": "ns/iter",
            "value": "132818",
            "range": "± 1",
            "category": "proto_run_V03",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86",
            "group": "below_ms"
          },
          {
            "name": "ihi5",
            "unit": "ns/iter",
            "value": "3513482",
            "range": "± 1",
            "category": "proto_run_V03",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86",
            "group": "medium"
          },
          {
            "name": "handle_init_hello",
            "unit": "ns/iter",
            "value": "102794703",
            "range": "± 1",
            "category": "proto_run_V03",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86",
            "group": "long"
          },
          {
            "name": "ihi4",
            "unit": "ns/iter",
            "value": "20999",
            "range": "± 1",
            "category": "proto_run_V03",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86",
            "group": "below_ms"
          },
          {
            "name": "ici3",
            "unit": "ns/iter",
            "value": "15900",
            "range": "± 1",
            "category": "proto_run_V03",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86",
            "group": "below_ms"
          },
          {
            "name": "ihr6",
            "unit": "ns/iter",
            "value": "20138",
            "range": "± 1",
            "category": "proto_run_V03",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86",
            "group": "below_ms"
          },
          {
            "name": "ihi6",
            "unit": "ns/iter",
            "value": "2828463",
            "range": "± 1",
            "category": "proto_run_V03",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86",
            "group": "medium"
          },
          {
            "name": "ihi8",
            "unit": "ns/iter",
            "value": "16201",
            "range": "± 1",
            "category": "proto_run_V03",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86",
            "group": "below_ms"
          },
          {
            "name": "rhi3",
            "unit": "ns/iter",
            "value": "15890",
            "range": "± 1",
            "category": "proto_run_V03",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86",
            "group": "below_ms"
          },
          {
            "name": "icr2",
            "unit": "ns/iter",
            "value": "112179",
            "range": "± 1",
            "category": "proto_run_V03",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86",
            "group": "below_ms"
          },
          {
            "name": "ihr7",
            "unit": "ns/iter",
            "value": "2831018",
            "range": "± 1",
            "category": "proto_run_V03",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86",
            "group": "medium"
          },
          {
            "name": "handle_initiation",
            "unit": "ns/iter",
            "value": "12346611",
            "range": "± 1",
            "category": "proto_run_V03",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86",
            "group": "medium"
          },
          {
            "name": "ici4",
            "unit": "ns/iter",
            "value": "15870",
            "range": "± 1",
            "category": "proto_run_V03",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86",
            "group": "below_ms"
          },
          {
            "name": "ihi2",
            "unit": "ns/iter",
            "value": "271",
            "range": "± 1",
            "category": "proto_run_V03",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86",
            "group": "below_us"
          },
          {
            "name": "ihr5",
            "unit": "ns/iter",
            "value": "87840422",
            "range": "± 1",
            "category": "proto_run_V03",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86",
            "group": "long"
          },
          {
            "name": "ihr4",
            "unit": "ns/iter",
            "value": "20438",
            "range": "± 1",
            "category": "proto_run_V03",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86",
            "group": "below_ms"
          },
          {
            "name": "rhr7",
            "unit": "ns/iter",
            "value": "15889",
            "range": "± 1",
            "category": "proto_run_V03",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86",
            "group": "below_ms"
          },
          {
            "name": "handle_resp_hello",
            "unit": "ns/iter",
            "value": "87906766",
            "range": "± 1",
            "category": "proto_run_V03",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86",
            "group": "long"
          },
          {
            "name": "handle_resp_conf",
            "unit": "ns/iter",
            "value": "2828493",
            "range": "± 1",
            "category": "proto_run_V03",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86",
            "group": "medium"
          },
          {
            "name": "rhi7",
            "unit": "ns/iter",
            "value": "19075",
            "range": "± 1",
            "category": "proto_run_V03",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86",
            "group": "below_ms"
          },
          {
            "name": "handle_init_conf",
            "unit": "ns/iter",
            "value": "3208193",
            "range": "± 1",
            "category": "proto_run_V03",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86",
            "group": "medium"
          },
          {
            "name": "rhr5",
            "unit": "ns/iter",
            "value": "3453601",
            "range": "± 1",
            "category": "proto_run_V03",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86",
            "group": "medium"
          },
          {
            "name": "rhr4",
            "unit": "ns/iter",
            "value": "139150",
            "range": "± 1",
            "category": "proto_run_V03",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86",
            "group": "below_ms"
          },
          {
            "name": "ihi7",
            "unit": "ns/iter",
            "value": "2851215",
            "range": "± 1",
            "category": "proto_run_V03",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86",
            "group": "medium"
          },
          {
            "name": "rhr6",
            "unit": "ns/iter",
            "value": "5631007",
            "range": "± 1",
            "category": "proto_run_V03",
            "sampleSize": "1",
            "os": "linux",
            "arch": "x86",
            "group": "medium"
          }
        ]
      }
    ]
  },
  "groupBy": [
    "os",
    "arch",
    "category",
    "group"
  ],
  "schema": [
    "os",
    "arch",
    "category",
    "group",
    "name"
  ]
}